name: 'Mark new issues with needs-triage label'

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label-new-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: initial labelling
        uses: andymckay/labeler@master
        with:
          add-labels: "needs-triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}